//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunodia.ClassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAttendee
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> PayerId { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<int> RegistrationTypeId { get; set; }
        public bool Attending { get; set; }
        public Nullable<System.DateTime> QBDate { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual RegistrationType RegistrationType { get; set; }
    }
}
