//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunodia.ClassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMaterial
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string MaterialName { get; set; }
        public decimal CostToStudent { get; set; }
        public decimal CostToOrg { get; set; }
        public string PurchaseOptions { get; set; }
        public Nullable<int> VendorId { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
