//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunodia.ClassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventbriteEvents = new HashSet<EventbriteEvent>();
            this.EventCost2Student = new HashSet<EventCost2Student>();
            this.MiscTransactions = new HashSet<MiscTransaction>();
            this.EventStudents = new HashSet<EventStudent>();
            this.EventTransactions = new HashSet<EventTransaction>();
            this.EventVenues = new HashSet<EventVenue>();
            this.MiscTransactions1 = new HashSet<MiscTransaction>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<System.DateTime> CourseDate { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<int> CourseFormatId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> BookCost { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> QuickBooksDate { get; set; }
        public bool Complete { get; set; }
        public Nullable<decimal> RegistrationCost { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Frequency { get; set; }
        public string CourseType { get; set; }
        public string NickName { get; set; }
        public bool Active { get; set; }
        public Nullable<int> FacilitatorId { get; set; }
        public Nullable<int> FrequencyId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual CourseFormat CourseFormat { get; set; }
        public virtual Cours Cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventbriteEvent> EventbriteEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventCost2Student> EventCost2Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscTransaction> MiscTransactions { get; set; }
        public virtual Person Person { get; set; }
        public virtual Frequency Frequency1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventStudent> EventStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTransaction> EventTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventVenue> EventVenues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscTransaction> MiscTransactions1 { get; set; }
    }
}
