//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunodia.ClassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventTransaction()
        {
            this.EventTransactionComments = new HashSet<EventTransactionComment>();
            this.EventTransactionStudents = new HashSet<EventTransactionStudent>();
        }
    
        public int Id { get; set; }
        public int EventId { get; set; }
        public decimal Amount { get; set; }
        public bool FHICredit { get; set; }
        public string Description { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> TransactionCategoryId { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual TransactionCategory TransactionCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTransactionComment> EventTransactionComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTransactionStudent> EventTransactionStudents { get; set; }
    }
}
