//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunodia.ClassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTransactionStudent
    {
        public int Id { get; set; }
        public int EventTransactionId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> RegistrationTypeId { get; set; }
    
        public virtual EventTransaction EventTransaction { get; set; }
        public virtual Person Person { get; set; }
        public virtual RegistrationType RegistrationType { get; set; }
    }
}
