//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunodia.ClassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCost2Student
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string CostDescription { get; set; }
        public decimal Cost { get; set; }
        public bool Required { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
