//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunodia.ClassManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fhiEntities : DbContext
    {
        public fhiEntities()
            : base("name=fhiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QBAccount> QBAccounts { get; set; }
        public virtual DbSet<RegistrationType> RegistrationTypes { get; set; }
        public virtual DbSet<vwRegistrationTotal> vwRegistrationTotals { get; set; }
        public virtual DbSet<vwStudentTotal> vwStudentTotals { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BooksPerClass> BooksPerClasses { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<ClassAttendee> ClassAttendees { get; set; }
        public virtual DbSet<CourseCert> CourseCerts { get; set; }
        public virtual DbSet<CourseFormat> CourseFormats { get; set; }
        public virtual DbSet<CourseMaterial> CourseMaterials { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<EventbriteEvent> EventbriteEvents { get; set; }
        public virtual DbSet<EventCost2Student> EventCost2Student { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventStudent> EventStudents { get; set; }
        public virtual DbSet<EventTransaction> EventTransactions { get; set; }
        public virtual DbSet<EventTransactionComment> EventTransactionComments { get; set; }
        public virtual DbSet<EventTransactionStudent> EventTransactionStudents { get; set; }
        public virtual DbSet<EventVenue> EventVenues { get; set; }
        public virtual DbSet<Frequency> Frequencies { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<MiscTransaction> MiscTransactions { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonGroup> PersonGroups { get; set; }
        public virtual DbSet<StudentCost> StudentCosts { get; set; }
        public virtual DbSet<TransactionCategory> TransactionCategories { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
        public virtual DbSet<VenueType> VenueTypes { get; set; }
        public virtual DbSet<vwEventTransaction> vwEventTransactions { get; set; }
        public virtual DbSet<vwFullPeople> vwFullPeoples { get; set; }
        public virtual DbSet<vwGroup> vwGroups { get; set; }
    }
}
