//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunodia.ClassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiscTransaction
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public Nullable<int> PayerId { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<System.DateTime> QBDate { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> QBAccount { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Event Event1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual PaymentMethod PaymentMethod1 { get; set; }
        public virtual QBAccount QBAccount1 { get; set; }
    }
}
