//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunodia.ClassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEventTransaction
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public bool FHICredit { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> RegistrationTypeId { get; set; }
        public string RegistrationType { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> fee { get; set; }
    }
}
