//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunodia.ClassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPaymentExpens
    {
        public System.DateTime DateAdded { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string PaymentMethod { get; set; }
        public decimal Percentage { get; set; }
        public decimal PlusFee { get; set; }
        public Nullable<decimal> fee { get; set; }
    }
}
