//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunodia.ClassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStudentTotal
    {
        public int classid { get; set; }
        public Nullable<int> StudentCount { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
    }
}
